#!/usr/bin/env bash
#
# post-receive hook
# Deploys to production after a push.
# Only the master reference will trigger a deployment.

while read oldrev newrev ref
do
	if [[ $ref =~ .*/master$ ]];
	then
		echo "$ref: deploying to production."
		git --work-tree=/var/www/html --git-dir=/home/roger/www checkout -f
	else
		echo "$ref: nothing will be deployed to production."
	fi
done
